<SHADER>
	<serialise_version>5</serialise_version>
	<shader_version>0</shader_version>
	<TECHNIQUES>
		<TECHNIQUE>
			<serialise_version>2</serialise_version>
			<name>Deferred Alpha</name>
			<source>shaders/vfx_burning_head_lava.xml.hlsl</source>
			<svt>SVT_DEFERRED_ALPHA</svt>
			<tt>TT_DISPLACEMENT_ALT3</tt>
			<stencil_ref>
				<stencil_ref_val>1</stencil_ref_val>
			</stencil_ref>
			<model>SHADER_MODEL_5_0</model>
			<primitive_topology>PT_TRIANGLELIST</primitive_topology>
			<vs>vs40_main</vs>
			<ps>ps_main_deferred_alpha</ps>
			<gs/>
			<hs/>
			<ds/>
			<cs/>
			<rasterizer_state>
				<fill_mode>FM_SOLID</fill_mode>
				<cull_mode>CULL_MODE_CCW</cull_mode>
				<front_counter_clockwise>0</front_counter_clockwise>
				<depth_bias>0</depth_bias>
				<depth_bias_clamp>0.000000</depth_bias_clamp>
				<slope_scaled_depth_bias>0.000000</slope_scaled_depth_bias>
				<depth_clip_enable>1</depth_clip_enable>
				<scissor_enable>0</scissor_enable>
				<multisample_enable>0</multisample_enable>
				<antialiased_line_enable>0</antialiased_line_enable>
				<forced_sample_count>0</forced_sample_count>
				<enable_conservative_rasterization>false</enable_conservative_rasterization>
			</rasterizer_state>
			<depth_stencil_state>
				<depth_enable>1</depth_enable>
				<depth_write_mask>DEPTH_WRITE_MASK_ZERO</depth_write_mask>
				<depth_function>CF_LESSEQUAL</depth_function>
				<stencil_enable>0</stencil_enable>
				<stencil_read_mask>255</stencil_read_mask>
				<stencil_write_mask>255</stencil_write_mask>
				<front_face>
					<stencil_fail_operation>SO_KEEP</stencil_fail_operation>
					<stencil_depth_fail_operation>SO_KEEP</stencil_depth_fail_operation>
					<stencil_pass_operation>SO_KEEP</stencil_pass_operation>
					<stencil_function>CF_ALWAYS</stencil_function>
				</front_face>
				<back_face>
					<stencil_fail_operation>SO_KEEP</stencil_fail_operation>
					<stencil_depth_fail_operation>SO_KEEP</stencil_depth_fail_operation>
					<stencil_pass_operation>SO_KEEP</stencil_pass_operation>
					<stencil_function>CF_ALWAYS</stencil_function>
				</back_face>
			</depth_stencil_state>
			<blend_state>
				<blend_factor_r>1.000000</blend_factor_r>
				<blend_factor_g>1.000000</blend_factor_g>
				<blend_factor_b>1.000000</blend_factor_b>
				<blend_factor_a>1.000000</blend_factor_a>
				<alpha_to_coverage_enable>0</alpha_to_coverage_enable>
				<independent_blend_enable>0</independent_blend_enable>
				<render_target_0>
					<blend_enable>1</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_INV_SRC_ALPHA</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_SRC_ALPHA</source_blend_alpha>
					<destination_blend_alpha>B_INV_SRC_ALPHA</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_ALL</render_target_write_mask>
				</render_target_0>
				<render_target_1>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_1>
				<render_target_2>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_2>
				<render_target_3>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_3>
				<render_target_4>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_4>
				<render_target_5>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_5>
				<render_target_6>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_6>
				<render_target_7>
					<blend_enable>0</blend_enable>
					<source_blend>B_ONE</source_blend>
					<destination_blend>B_ZERO</destination_blend>
					<blend_operation>BO_ADD</blend_operation>
					<source_blend_alpha>B_ONE</source_blend_alpha>
					<destination_blend_alpha>B_ZERO</destination_blend_alpha>
					<blend_operation_alpha>BO_ADD</blend_operation_alpha>
					<render_target_write_mask>CWE_NONE</render_target_write_mask>
				</render_target_7>
			</blend_state>
		</TECHNIQUE>
	</TECHNIQUES>
	<flags>2</flags>
	<PARAM_COMMENTS/>
</SHADER>
